//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVM.API.Services.SQL {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVM.API.Services.SQL.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM coin
        ///WHERE id = @p_id;.
        /// </summary>
        internal static string Coin_GetCoinById {
            get {
                return ResourceManager.GetString("Coin_GetCoinById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM drink
        ///WHERE id = @p_id.
        /// </summary>
        internal static string Drink_DeleteDrink {
            get {
                return ResourceManager.GetString("Drink_DeleteDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM drinks.
        /// </summary>
        internal static string Drink_GetAllDrinks {
            get {
                return ResourceManager.GetString("Drink_GetAllDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM drink
        ///WHERE id = @p_id.
        /// </summary>
        internal static string Drink_GetDrinkById {
            get {
                return ResourceManager.GetString("Drink_GetDrinkById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO drink
        ///VALUES(
        ///@p_id,
        ///@p_name,
        ///@p_image,
        ///@p_cost)
        ///ON CONFLICT(id) DO
        ///UPDATE drink
        ///SET
        ///name = @p_name,
        ///image = @p_image,
        ///cost = @p_cost
        ///WHERE id = @p_id.
        /// </summary>
        internal static string Drink_SaveDrink {
            get {
                return ResourceManager.GetString("Drink_SaveDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM vendingmachine
        ///WHERE id = @p_id.
        /// </summary>
        internal static string VendingMachine_DeleteMachine {
            get {
                return ResourceManager.GetString("VendingMachine_DeleteMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM vendingmachine.
        /// </summary>
        internal static string VendingMachine_GetAllMachines {
            get {
                return ResourceManager.GetString("VendingMachine_GetAllMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM vendingmachine
        ///where secretcode = @p_secretcode;.
        /// </summary>
        internal static string VendingMachine_GetVendingMachineBySecretCode {
            get {
                return ResourceManager.GetString("VendingMachine_GetVendingMachineBySecretCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO vendingmachine
        ///VALUES (@p_id, @p_secretcode)
        ///ON CONFLICT(id) DO
        ///UPDATE vendingmachine
        ///SET
        ///secretcode = @p_secretcode
        ///WHERE id = @p_id.
        /// </summary>
        internal static string VendingMachine_SaveMachine {
            get {
                return ResourceManager.GetString("VendingMachine_SaveMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM vmcoin
        ///WHERE vmid = @p_id;.
        /// </summary>
        internal static string VMCoin_GetVMCoinsByVMId {
            get {
                return ResourceManager.GetString("VMCoin_GetVMCoinsByVMId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM vmdrink
        ///WHERE vmid = @p_id.
        /// </summary>
        internal static string VMDrink_GetVMDrinksByVMId {
            get {
                return ResourceManager.GetString("VMDrink_GetVMDrinksByVMId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM vmdrink
        ///WHERE id = @p_id;.
        /// </summary>
        internal static string VMDrink_RemoveVMDrink_sql {
            get {
                return ResourceManager.GetString("VMDrink_RemoveVMDrink_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO vmdrink
        ///VALUES (
        ///@p_id,
        ///@p_vmid,
        ///@p_drinkid,
        ///@p_count)
        ///ON CONFLICT(id) DO
        ///UPDATE vmdrink
        ///SET 
        ///vmid = @p_vmid,
        ///drinkid = @p_drinkid,
        ///count = @p_count
        ///WHERE id = @p_id.
        /// </summary>
        internal static string VMDrink_SaveVMDrink {
            get {
                return ResourceManager.GetString("VMDrink_SaveVMDrink", resourceCulture);
            }
        }
    }
}
